.TH "Circulo" 3 "Wed Oct 31 2018" "Version 1.0.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Circulo \- The \fBCirculo\fP class: Desenha circulos\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <circulo\&.h>\fP
.PP
Inherits \fBFiguraGeometrica\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCirculo\fP (int _x0, int _y0, int _r, int _fillmode, char _brush)"
.br
.RI "\fBCirculo\fP: Construtor com argumentos\&. "
.ti -1c
.RI "void \fBdraw\fP (\fBScreen\fP &t)"
.br
.RI "draw: Desenha um circulo na tela "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The \fBCirculo\fP class: Desenha circulos\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Circulo::Circulo (int _x0, int _y0, int _r, int _fillmode, char _brush)"

.PP
\fBCirculo\fP: Construtor com argumentos\&. 
.PP
\fBParameters:\fP
.RS 4
\fI_x0\fP Coordenada x inicial 
.br
\fI_y0\fP Coordenada y inicial 
.br
\fI_r\fP Raio 
.br
\fI_fillmode\fP Determina se o circulo é preenchido ou não 
.br
\fI_brush\fP Caractere de desenho 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void Circulo::draw (\fBScreen\fP & t)\fC [virtual]\fP"

.PP
draw: Desenha um circulo na tela 
.PP
\fBParameters:\fP
.RS 4
\fIt\fP Tela 
.RE
.PP

.PP
Implements \fBFiguraGeometrica\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
